
name: build, test and release

on:
  push:
    tags:
      "v*.*.*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
          - x64
        node:
          - 22
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        include:
          - arch: x86
            node: 22
            os: windows-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - run: npm install
      - run: npm test
  build:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
          - x64
        os:
          - macos-latest
          - ubuntu-22.04
          - windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          architecture: ${{ matrix.arch }}
      - run: npm install
      - run: npm run prebuild
        if: matrix.os != 'macos-latest'
      - run: npm run prebuild-darwin-x64+arm64
        if: matrix.os == 'macos-latest'
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: prebuilds
          retention-days: 1
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org/'
      - name: publish to npmjs
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      
