name: test downloaded npm package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org/'
      - run: |
          npm install @fqlan/node-addon-example
          npm install
          cat package.json
# npm test
    
